jasypt:
  encryptor:
    password: mycloud-salt

spring:
  profiles:
    include: service-pro
  jpa:
    database: mysql
    show-sql: true
#    generate-ddl: false
    open-in-view: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://120.79.12.83:3307/mycloud_sso?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ENC(W9Fdtjzo7LH1xPfw6ygkKnrJx5TR1yDy)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间(毫秒)
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
    filters: stat, wall, log4j
    # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  redis:
    host: 120.79.12.83
    password: ENC(W9Fdtjzo7LH1xPfw6ygkKnrJx5TR1yDy)
    port: 6379
    timeout: 5000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 0
        max-wait: 6000