server:
  port: 10005
spring:
  application:
    name: mycloud-movie-client
  profiles:
    active: dev
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

########## 自定义 ###########

app:
  name: 电影应用客户端
  workerId: 1
  dataCenterId: 1
  company: c式
  email: season@email
  code: mycloud-movie-client


#线程池配置
threads:
  data:
    coreSize: 10
    maxSize: 30
    queueCapacity: 20

