jasypt:
  encryptor:
    password: mycloud-salt

spring:
  datasource:
    url: jdbc:mysql://localhost/mycloud_movie?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ENC(W9Fdtjzo7LH1xPfw6ygkKnrJx5TR1yDy)
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.season.movie.dao.entity
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.season.movie.dao.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
