jasypt:
  encryptor:
    password: mycloud-salt

spring:
  datasource:
    url: jdbc:mysql://120.79.12.83:3306/mycloud_movie?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: season
    password: ENC(3aQyMf0tAKfF8ziExb60gMe1rrTDn0z7)
    sql-script-encoding: UTF-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.season.movie.dao.entity
  mapper-locations: classpath:mapper/*.xml
  enum-package: com.season.movie.dao.enums  #自定义的
mapper:
  mappers: com.season.movie.dao.MyMapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


file:
  video:
    path: ~/mycloud/videos/