server:
  port: 10006
spring:
  application:
    name: mycloud-movie-admin
  profiles:
    active: dev
    include: service
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

########## 自定义 ###########

app:
  name: 电影应用后台
  workerId: 1
  dataCenterId: 1
  company: c式
  email: season@email
  code: mycloud-movie-admin
