spring:
  profiles:
    include: dao-pro,service-pro
  redis:
    host: 120.79.12.83
    password: ENC(W9Fdtjzo7LH1xPfw6ygkKnrJx5TR1yDy)
    port: 6379
    timeout: 0
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        min-idle: 0
        max-wait: 6000